#!/usr/bin/env bash
# enforce HTTPS traffic so that no unencrypted traffic is possible.
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend www-http
    bind *:80
    mode http
    option forwardfor
    reqadd X-Forwarded-Proto:\ http
    acl is_www path_beg -i /  # Define an ACL to match requests for subdomain
    redirect scheme https if !{ ssl_fc } is_www  # Redirect HTTP to HTTPS

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.wamoni.tech/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    mode http
    balance roundrobin
    server web-server 127.0.0.1:80 check

listen stats
    bind *:8404
    stats enable
    stats uri /stats
    stats auth username:password