#!/usr/bin/bash
# Check if all required parameters are provided

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables

path_to_file="$1"
ip_address="$2"
username="$3"
ssh_key="$4"

# Transfer the file using scp-disable strict host key check

scp -o StrictHostKeyChecking=no -i "$ssh_key"
"$path_to_file" "$username"@"$ip_address":~/

echo "File transferred successfully to $ip_address"
