#!/usr/bin/bash
# Check if all required parameters are provided

if [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

else
# Transfer the file using scp-disable strict host key check

    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/

    echo "File transferred successfully to $ip_address"

fi
