#!/usr/bin/env bash

sudo apt-get update

sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'

# Simple HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx
sudo /etc/init.d/nginx restart
