#!/usr/bin/env bash

sudo apt-get update

sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'

# replace default nginx welcome
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Restart Nginx
sudo service nginx start
