#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get -y install nginx

# Replace default Nginx index page
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

# Configure redirection in the Nginx default site configuration
REDIRECT_CONFIG="\
location /redirect_me {\n\
    return 301 http://github.com/;\n\
}"

sudo sed -i "/location \/ {/,/}/{//!d}; /location \/ {/a $REDIRECT_CONFIG" /etc/nginx/sites-available/default

sudo service nginx start
