#!/usr/bin/env bash
#redirection

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
# Replace default Nginx index page
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Configure redirection in the Nginx default site configuration
REDIRECT_CONFIG='redirect_me https://www.youtube.com/ permanent;'

sudo sed -i '/listen 80 default_server/a rewrite ^/'$REDIRECT_CONFIG" /etc/nginx/sites-available/default

sudo service nginx restart
