#!/usr/bin/env bash

sudo apt-get update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Step 3: Configure Nginx for the custom 404 page
sudo tee /etc/nginx/sites-available/custom_404 <<EOF
server {
    listen 80;
    server_name _;

    location / {
        root /var/www/html;
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOF

# Step 4: Enable the custom 404 site
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Step 5: Test Nginx configuration and reload
sudo nginx -t
sudo service nginx reload
