#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx for custom 404 page
NGINX_CONFIG="/etc/nginx/sites-available/default"
CUSTOM_404_CONFIG="\
    error_page 404 /404.html;\n\
    location = /404.html {\n\
        internal;\n\
    }"

# Add custom 404 config after server_name line
sudo sed -i "/server_name _;/a $CUSTOM_404_CONFIG" $NGINX_CONFIG

sudo service nginx start