#!/usr/bin/env bash
#nginx instalation

sudo apt-get update
sudo apt-get -y install nginx
# add a custom HTTP header to the Nginx configuration file
sudo sed -i "/http {/a\ add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart