#!/usr/bin/env bash
# Install and configure HAproxy 

# Update package list & install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Add servers and configure
sudo echo "
frontend wamoni-front
	 bind *:80
	 mode http
	 default_backend wamoni-back

backend wamoni-back
	balance roundrobin
	server 225673-web-01 54.158.221.58:80 check
	server 225673-web-02 35.153.226.235:80 check
" >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
