#!/usr/bin/env bash

# Install and configure HAproxy 

# Update package list & install HAProxy
sudo apt-get update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*

# Configure HAProxy
configuration="\
frontend http-in
	 bind *:80
	 mode http
    	 default_backend servers

backend webservers
    	balance roundrobin
    	server web-01 225673-web-01 54.158.221.58:80 check
    	server web-02 225673-web-02 52.23.245.24:80 check
"
# Enable HAProxy as an init service
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$configuration" >> /etc/haproxy/haproxy.cfg

# Start HAProxy
sudo service haproxy start
