#!/usr/bin/env bash

# Install and configure HAproxy 

# Update package list & install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 225673-web-01 54.158.221.58:80 check
    server web-02 225673-web-02 52.23.245.24:80 check
EOF

# Enable HAProxy as an init service
sudo service haproxy enable

# Start HAProxy
sudo service haproxy start
