#!/usr/bin/env bash
#ensure nginx listens to port 80 of all IPv4 IPs

#ensure nginx is running
sudo service nginx status || sudo service nginx start

#backup current file
sudo mv /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default-old

#configure nginx with a symbolic link
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# reload{not restart 2 avoid downtime} nginx
sudo service nginx reload
