#!/usr/bin/env bash
# change user to nginx and port

# change user to nginx from www-data
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

# change the default listening port from 80 to 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# grant read write permission
chmod 644 /etc/nginx/nginx.conf

pkill apache2
sudo -u nginx service nginx start